default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Prepare dependencies for building app"
  lane :prepare_build do |options|
    update_build_number
    push_to_git_remote unless options[:skip_push]
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    install_signing
    build_app(
      project: "./ios/EuTambem.xcodeproj",
      scheme: "EuTambem")
    upload_to_testflight
  end

  desc "Install all certificates and provisioning profiles"
  lane :install_signing do
    sync_code_signing(type: "development", readonly: true)
    sync_code_signing(type: "appstore", readonly: true)
  end

  desc "Generate AppIcons for ios"
  lane :generate_app_icons do
    appicon(
      appicon_image_file: './app/img/AppIcon.png',
      appicon_path: './ios/EuTambem/Images.xcassets',
      appicon_devices: [:ipad, :iphone, :ios_marketing]
    )
  end

  desc "Update and tag the version/build"
  lane :update_build_number do
    build_number = ENV['CIRCLE_BUILD_NUM'] if ENV['CIRCLECI']

    increment_build_number(
      xcodeproj: "./ios/EuTambem.xcodeproj", 
      build_number: build_number
    )

    build_number = get_build_number(xcodeproj: "./ios/EuTambem.xcodeproj")
    version_number = get_version_number(xcodeproj: "./ios/EuTambem.xcodeproj")
    tag_name = "#{version_number}/#{build_number}"
    add_git_tag(tag: tag_name)

    UI.success("Success! New version: #{tag_name}")
  end
  
end
