default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    unless options[:build_number]
      UI.error "No build_number provided!"
      exit(1)
    end

    update_build_number build_number:options[:build_number]
    push_to_git_remote unless options[:skip_push]

    install_signing
    build_app(
      project: "./ios/EuTambem.xcodeproj",
      scheme: "EuTambem")
    upload_to_testflight
  end

  desc "Install all certificates and provisioning profiles"
  lane :install_signing do
    sync_code_signing(type: "development", readonly: true)
    sync_code_signing(type: "appstore", readonly: true)
  end

  desc "Generate AppIcons for ios"
  lane :generate_app_icons do
    appicon(
      appicon_image_file: './app/img/AppIcon.png',
      appicon_path: './ios/EuTambem/Images.xcassets',
      appicon_devices: [:ipad, :iphone, :ios_marketing]
    )
  end

  desc "Update and tag the version/build"
  lane :update_build_number do |options|

    increment_build_number(
      xcodeproj: "./ios/EuTambem.xcodeproj", 
      build_number: options[:build_number]
    )

    build_number = get_build_number(xcodeproj: "./ios/EuTambem.xcodeproj")
    version_number = get_version_number(xcodeproj: "./ios/EuTambem.xcodeproj")
    tag_name = "#{version_number}/#{build_number}"
    add_git_tag(tag: tag_name)

    UI.success("Success! New version: #{tag_name}")
  end
  
end
