default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    install_signing
    build_app(scheme: "EuTambem")
    upload_to_testflight
  end

  desc "Install all certificates and provisioning profiles"
  lane :install_signing do
    sync_code_signing(type: "development", readonly: true)
    sync_code_signing(type: "appstore", readonly: true)
  end

  desc "Generate AppIcons for ios"
  lane :generate_app_icons do
    appicon(
      appicon_image_file: '../app/img/AppIcon.png',
      appicon_path: 'EuTambem/Images.xcassets',
      appicon_devices: [:ipad, :iphone, :ios_marketing]
    )
      
  end
end
